'use strict';

// module.exports.Accordion = require('grommet/components/Accordion');
// module.exports.AccordionPanel = require('grommet/components/AccordionPanel');
// module.exports.announce = require('grommet/utils/Announcer').announce;
// module.exports.announcePageLoaded = require('grommet/utils/Announcer').announcePageLoaded;
// module.exports.Headline = require('grommet/components/Headline');
// module.exports.LoginForm = require('grommet/components/LoginForm');
// module.exports.Markdown  = require('grommet/components/Markdown');
// module.exports.Paragraph = require('grommet/components/Paragraph');
// module.exports.Table = require('grommet/components/Table');
// module.exports.TableRow = require('grommet/components/TableRow');
// module.exports.TextInput = require('grommet/components/TextInput');
module.exports.Anchor = require('grommet/components/Anchor');
module.exports.App = require('grommet/components/App');
module.exports.Article = require('grommet/components/Article');
module.exports.Box = require('grommet/components/Box');
module.exports.Button = require('grommet/components/Button');
module.exports.CheckBox = require('grommet/components/CheckBox');
module.exports.Footer = require('grommet/components/Footer');
module.exports.GrommetLogo = require('grommet/components/icons/Grommet');
module.exports.Header = require('grommet/components/Header');
module.exports.Heading = require('grommet/components/Heading');
module.exports.Image = require('grommet/components/Image');
module.exports.Label = require('grommet/components/Label');
module.exports.Layer = require('grommet/components/Layer');
module.exports.Menu = require('grommet/components/Menu');
module.exports.Notification = require('grommet/components/Notification');
module.exports.RadioButton = require('grommet/components/RadioButton');
module.exports.Search = require('grommet/components/Search');
module.exports.SearchAdvancedIcon = require('grommet/components/icons/base/SearchAdvanced');
module.exports.SearchInput = require('grommet/components/SearchInput');
module.exports.Section = require('grommet/components/Section');
module.exports.Sidebar = require('grommet/components/Sidebar');

module.exports.Split = require('grommet/components/Split');
module.exports.Tab = require('grommet/components/Tab');
module.exports.Tabs = require('grommet/components/Tabs');
module.exports.Tile = require('grommet/components/Tile');
module.exports.Tiles = require('grommet/components/Tiles');
module.exports.Title = require('grommet/components/Title');
module.exports.Image = require('grommet/components/Image');
module.exports.Toast = require( 'grommet/components/Toast');

/*** Icon */
module.exports.UserIcon = require('grommet/components/icons/base/User');
module.exports.SocialMailIcon = require('grommet/components/icons/base/SocialMail');
module.exports.PrintIcon = require('grommet/components/icons/base/Print');
module.exports.ClearOptionIcon = require('grommet/components/icons/base/ClearOption');
module.exports.DocUpdateIcon = require('grommet/components/icons/base/DocumentUpdate');
module.exports.EditIcon = require('grommet/components/icons/base/Edit');
module.exports.FilterIcon = require('grommet/components/icons/base/Filter');
module.exports.FavoriteIcon = require('grommet/components/icons/base/Favorite');
